#!/usr/bin/env python3
"""
Regenerate comparators_all.lib  -  the single consolidated comparator library.

Collects every comparator subckt from the per-cell libraries in this directory
into ONE file, renaming each with a rail suffix (5V0 / 3V3 / 1V8) so they coexist
without name clashes. Subckt BODIES are copied verbatim, so the combined file is
electrically identical to the sources -- edit the per-folder .lib files and re-run
this, never hand-edit comparators_all.lib.

  python gen_comparators_all.py
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent

# (lib path relative to here, [(old subckt name, new suffixed name), ...])
SRCS = [
    ("general_purpose/cmp_gp.lib",     [("CMP_NIN", "CMP_NIN_5V0"), ("CMP_PIN", "CMP_PIN_5V0")]),
    ("general_purpose_3v3/cmp_gp.lib", [("CMP_NIN", "CMP_NIN_3V3"), ("CMP_PIN", "CMP_PIN_3V3")]),
    ("general_purpose_1v8/cmp_gp.lib", [("CMP_NIN", "CMP_NIN_1V8"), ("CMP_PIN", "CMP_PIN_1V8")]),
    ("rail_to_rail_5v0/cmp_rr.lib",    [("CMP_RR", "CMP_RR_5V0")]),
    ("rail_to_rail_3v3/cmp_rr.lib",    [("CMP_RR", "CMP_RR_3V3")]),
    ("rail_to_rail_1v8/cmp_rr.lib",    [("CMP_RR", "CMP_RR_1V8")]),
]

# display grouping in the output file
SECTIONS = [
    ("GENERAL-PURPOSE  (two-stage; NMOS-input = high CM / PMOS-input = low CM)",
     ["CMP_NIN_5V0", "CMP_PIN_5V0", "CMP_NIN_3V3", "CMP_PIN_3V3", "CMP_NIN_1V8", "CMP_PIN_1V8"]),
    ("RAIL-TO-RAIL INPUT  (complementary pairs summed in a folded cascode)",
     ["CMP_RR_5V0", "CMP_RR_3V3", "CMP_RR_1V8"]),
]
OUT = "comparators_all.lib"


def extract(path: Path, renames):
    rmap = dict(renames)
    blocks, cur, name = [], None, None
    for ln in path.read_text().splitlines():
        m = re.match(r"^\.subckt\s+(\S+)", ln, re.I)
        if m:
            old = m.group(1)
            name = rmap.get(old, old)
            cur = [re.sub(r"(^\.subckt\s+)" + re.escape(old), r"\1" + name, ln, flags=re.I)]
            continue
        if cur is not None:
            if re.match(r"^\.ends", ln, re.I):
                cur.append(f".ends {name}")
                blocks.append((name, cur)); cur = name = None
            else:
                cur.append(ln)
    return blocks


def main():
    bodies = {}
    for rel, ren in SRCS:
        for name, body in extract(HERE / rel, ren):
            bodies[name] = "\n".join(body)
    names = [n for _, g in SECTIONS for n in g]

    hdr = ["* " + "=" * 74,
           "* comparators_all.lib  -  AutoHV BiCMOS 180  (single consolidated library)",
           "* " + "-" * 74,
           "* AUTO-GENERATED by gen_comparators_all.py from the per-cell libraries in",
           "* this directory. Every comparator subckt is collected here under a",
           "* RAIL-SUFFIXED name so they coexist in one file. Bodies are verbatim copies",
           "* (electrically identical) -- edit the per-folder libs and regenerate; do not",
           "* hand-edit this file.",
           "*",
           "* Use:  .include the PDK model lib AND this file, then instance by name:",
           '*   .include "<...>/autohv_bicmos180_case.lib"',
           '*   .include "comparators_all.lib"',
           "*   X1 inp inn out vdd 0 nb CMP_RR_5V0 IREF=5u FIN=1",
           "*   Ib vdd nb 5u",
           "*",
           "* Ports (all cells):  inp inn out vdd vss nb   (push IREF into nb; vdd/vss only).",
           "* Polarity        :  OUT high when V(inp) > V(inn).",
           "* Naming          :  CMP_<type>_<rail>  -  type NIN/PIN (general-purpose,",
           "*                    NMOS-/PMOS-input) or RR (rail-to-rail input);",
           "*                    rail 5V0 / 3V3 / 1V8.",
           "* Knobs/specs/sign-off: README.md, general_purpose/DESIGN_NOTES.md, folder READMEs.",
           "*",
           f"* Contents ({len(names)} subckts):"]
    hdr += [f"*   {n}" for n in names]
    hdr += ["* " + "=" * 74, ""]

    parts = ["\n".join(hdr)]
    for title, group in SECTIONS:
        parts.append(f"\n* {'='*74}\n* {title}\n* {'='*74}\n")
        for n in group:
            parts.append(bodies[n] + "\n")
    (HERE / OUT).write_text("\n".join(parts))
    print(f"wrote {OUT}: {len(names)} subckts -> {', '.join(names)}")


if __name__ == "__main__":
    main()
