"""
mirror_lib.py -- deck builders + ngspice runner for the PMOS current-mirror
characterization study (AutoHV BiCMOS180, 5 V domain / PMOS50).

Topologies (all PMOS50, source=Vdd, bulk=Vdd so V_SB=0):
  MIR_S  : simple mirror  (diode input device + output device on shared gate)
  MIR_CS : standard cascode (cascode gate from a diode-connected stack)
  MIR_CW : wide-swing cascode (cascode gate from an ideal Vdd-referenced source;
           one self-biased variant built separately for cross-check)

Controlled-comparison rule (brief 2): input diode device and output device are
IDENTICAL across MIR_S / MIR_CS / MIR_CW; the cascode adds a series device sized
the same as the output device. Only the cascode device differs.

I_in is an ideal forced current source (instrument). No resistors anywhere.
"""
import os, subprocess, tempfile, re
import numpy as np

ROOT = "/Users/christopherklaus/Documents/ngspice/autohv-bicmos180-pdk"
LIB  = os.path.join(ROOT, "autohv_bicmos180_case.lib")
HERE = os.path.dirname(os.path.abspath(__file__))
NETLISTS = os.path.join(HERE, "netlists")
RAW  = os.path.join(HERE, "raw")
for d in (NETLISTS, RAW):
    os.makedirs(d, exist_ok=True)


# ---------------------------------------------------------------------------
# device-instance emitter.  geometry goes in the deck, never in a script param.
# ---------------------------------------------------------------------------
def _dev(name, d, g, s, b, W, L, M):
    return f"X{name} {d} {g} {s} {b} PMOS50 W={W:.6g} L={L:.6g} M={int(M)}"


def build_core(topo, geom, node_out="nout"):
    """Return (lines, out_node) for the mirror core.  geom is a dict with
    Win,Lin,Min (input diode device), Wout,Lout,Mout (output device),
    Wc,Lc,Mc (cascode device, MIR_CS/CW only), and for MIR_CW: vbias (V below Vdd
    for the cascode gate)."""
    L = []
    if topo == "MIR_S":
        L.append(_dev("in",  "nin", "nin", "vdd", "vdd",
                      geom["Win"], geom["Lin"], geom["Min"]))
        L.append(_dev("out", node_out, "nin", "vdd", "vdd",
                      geom["Wout"], geom["Lout"], geom["Mout"]))
    elif topo == "MIR_CS":
        # input diode stack: vdd -> n1 (top diode) -> n2 (cascode diode) -> Iin
        L.append(_dev("in",   "n1", "n1", "vdd", "vdd",
                      geom["Win"], geom["Lin"], geom["Min"]))
        L.append(_dev("incs", "n2", "n2", "n1",  "vdd",
                      geom["Wc"], geom["Lc"], geom["Mc"]))
        # output stack: vdd -> n3 (top, gate=n1) -> nout (cascode, gate=n2)
        L.append(_dev("out",  "n3", "n1", "vdd", "vdd",
                      geom["Wout"], geom["Lout"], geom["Mout"]))
        L.append(_dev("outcs", node_out, "n2", "n3", "vdd",
                      geom["Wc"], geom["Lc"], geom["Mc"]))
    elif topo == "MIR_CW":
        # high-swing (Sooch) cascode.  Mirror gate 'ng' is taken at the TOP of the
        # input stack (= Iin node = drain of input cascode); each top device's own
        # drain (nA / nB) is a separate internal node held at ~Vov below Vdd by the
        # cascode, so BOTH top devices sit at V_SD = V_ov (input matches output).
        #   input top  Xin  : S=vdd  G=ng  D=nA
        #   input casc Xincw : S=nA   G=ncw D=ng   (Iin sinks from ng)
        L.append(_dev("in",   "nA", "ng", "vdd", "vdd",
                      geom["Win"], geom["Lin"], geom["Min"]))
        L.append(_dev("incw", "ng", "ncw", "nA", "vdd",
                      geom["Wc"], geom["Lc"], geom["Mc"]))
        # ideal wide-swing bias: ncw = vdd - vbias
        L.append(f"Vbcw vdd ncw {geom['vbias']:.6g}")
        #   output top  Xout  : S=vdd G=ng  D=nB
        #   output casc Xoutcw: S=nB  G=ncw D=nout
        L.append(_dev("out",  "nB", "ng", "vdd", "vdd",
                      geom["Wout"], geom["Lout"], geom["Mout"]))
        L.append(_dev("outcw", node_out, "ncw", "nB", "vdd",
                      geom["Wc"], geom["Lc"], geom["Mc"]))
    elif topo == "MIR_CW_SB":
        # self-biased high-swing: ncw generated by a W/4 diode branch carrying a
        # copy of Iin.  A quarter-width device has ~2x the overdrive, so its VSG =
        # Vth + 2*Vov, placing ncw = vdd-(Vth+2Vov) = vdd-(VSG+Vov): the exact
        # wide-swing bias, with no ideal source.
        L.append(_dev("in",   "nA", "ng", "vdd", "vdd",
                      geom["Win"], geom["Lin"], geom["Min"]))
        L.append(_dev("incw", "ng", "ncw", "nA", "vdd",
                      geom["Wc"], geom["Lc"], geom["Mc"]))
        L.append(f"Ibias ncw 0 {geom['Iin']:.9g}")
        L.append(_dev("bias", "ncw", "ncw", "vdd", "vdd",
                      geom["Wc"]/4.0, geom["Lc"], geom["Mc"]))
        L.append(_dev("out",  "nB", "ng", "vdd", "vdd",
                      geom["Wout"], geom["Lout"], geom["Mout"]))
        L.append(_dev("outcw", node_out, "ncw", "nB", "vdd",
                      geom["Wc"], geom["Lc"], geom["Mc"]))
    else:
        raise ValueError(topo)
    return L, node_out


def _header(title, case, proc, mm, temp, mm_sigma=0):
    return [
        f".title {title}",
        f'.include "{LIB}"',
        f".param case={case} PROC_ON={proc} MM_ON={mm} MM_SIGMA={mm_sigma}",
        f".options temp={temp}",
    ]


def deck_dc(title, topo, geom, Iin, Vdd, vstart, vstop, vstep,
            case=0, proc=0, mm=0, temp=27, mm_sigma=0, outfile=None):
    """A .dc sweep of V_out.  Writes wrdata <outfile> with columns (Vout, Iout)."""
    lines = _header(title, case, proc, mm, temp, mm_sigma)
    lines += [f"Vdd vdd 0 {Vdd:.6g}", f"Iin nin_or 0 {Iin:.9g}"]
    core, outn = build_core(topo, geom, node_out="nout")
    # wire the ideal input current sink to the mirror input node.  MIR_S uses
    # node 'nin'; cascodes sink from 'n2'.  Rename via a 0-ohm-free alias:
    sink = {"MIR_S":"nin","MIR_CS":"n2","MIR_CW":"ng","MIR_CW_SB":"ng"}[topo]
    lines = [l.replace("nin_or", sink) for l in lines]
    lines += core
    lines.append(f"Vout {outn} 0 0")
    if outfile is None:
        outfile = os.path.join(RAW, "dc.dat")
    lines += [
        ".control",
        f"dc Vout {vstart:.6g} {vstop:.6g} {vstep:.6g}",
        f"wrdata {outfile} i(Vout)",   # i(Vout)>0 = current delivered into the load
        ".endc",
        ".end",
    ]
    return "\n".join(lines) + "\n", outfile


def deck_op(title, topo, geom, Iin, Vdd, vout, case=0, proc=0, mm=0, temp=27):
    """A single .op with V_out clamped; prints device operating point of the
    output device (and input diode device)."""
    lines = _header(title, case, proc, mm, temp)
    lines += [f"Vdd vdd 0 {Vdd:.6g}", f"Iin nin_or 0 {Iin:.9g}"]
    core, outn = build_core(topo, geom, node_out="nout")
    sink = {"MIR_S":"nin","MIR_CS":"n2","MIR_CW":"ng","MIR_CW_SB":"ng"}[topo]
    lines = [l.replace("nin_or", sink) for l in lines]
    lines += core
    lines.append(f"Vout {outn} 0 {vout:.6g}")
    # device handles
    outdev = "xout.m0"
    indev  = "xin.m0"
    probes = ["vth", "vdsat", "gm", "gds", "id", "gmbs", "vgs", "vds"]
    lines += [".control", "op"]
    for h in (indev, outdev):
        for p in probes:
            lines.append(f"print @m.{h}[{p}]")
    lines += [".endc", ".end"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# ngspice invocation
# ---------------------------------------------------------------------------
def run(deck, tag="deck"):
    """Run a deck through ngspice -b; return stdout text."""
    path = os.path.join(RAW, f"_{tag}.cir")
    with open(path, "w") as f:
        f.write(deck)
    p = subprocess.run(["ngspice", "-b", path], capture_output=True, text=True,
                       timeout=600)
    return p.stdout + "\n" + p.stderr


def read_wrdata(path):
    """Read a 2-column ngspice wrdata file -> (Vout[], Iout[])."""
    a = np.loadtxt(path)
    if a.ndim == 1:
        a = a.reshape(1, -1)
    return a[:, 0], a[:, 1]


_num = r"[-+0-9.eE]+"
def parse_op(text):
    """Parse '@m.xdev.m0[param] = value' lines -> nested dict {dev:{param:val}}."""
    out = {}
    for m in re.finditer(r"@m\.(x\w+\.m0)\[(\w+)\]\s*=\s*(" + _num + ")", text):
        dev, par, val = m.group(1), m.group(2), float(m.group(3))
        out.setdefault(dev, {})[par] = val
    return out


# ---------------------------------------------------------------------------
# sizing helpers
# ---------------------------------------------------------------------------
VT_THERMAL = 0.02585  # kT/q at 27C

def diode_op(W, L, Iin, Vdd=5.0, case=0, temp=27):
    """OP of a single diode-connected PMOS50 forced at Iin. Returns dict."""
    d = _header("diode", case, 0, 0, temp)
    d += [f"Vdd vdd 0 {Vdd:.6g}", f"Iin nd 0 {Iin:.9g}",
          _dev("d", "nd", "nd", "vdd", "vdd", W, L, 1)]
    for p in ("vth","vdsat","gm","gds","id","vgs"):
        d.append(f".control\nop\nprint @m.xd.m0[{p}]\n.endc") if False else None
    d += [".control", "op"]
    for p in ("vth","vdsat","gm","gds","id","vgs","cgg"):
        d.append(f"print @m.xd.m0[{p}]")
    d += [".endc", ".end"]
    op = parse_op(run("\n".join(d), "diode"))["xd.m0"]
    vsg = abs(op["vgs"]); vth = abs(op["vth"]); idd = abs(op["id"])
    vov = vsg - vth
    gm_id = op["gm"]/idd
    # EKV inversion coefficient from gm/Id (n~1.3): gm/Id=1/(n Vt (sqrt(IC+.25)+.5))
    n = 1.3
    x = 1.0/(gm_id*n*VT_THERMAL)          # = sqrt(IC+.25)+.5
    IC = (max(x-0.5, 1e-6))**2 - 0.25
    return dict(W=W, L=L, vov=vov, vdsat=op["vdsat"], vsg=vsg, vth=vth,
                id=idd, gm_id=gm_id, IC=max(IC, 0.0), gds=op["gds"])


def size_W_for_vov(L, Iin, target_vov=0.20, Wmin=0.5e-6, Wmax=4e-3,
                   Vdd=5.0, case=0, temp=27, tol=2e-3):
    """Bisection on W so that Vov = |VSG|-|Vth| == target_vov.  Larger W -> lower
    Vov.  Returns (W, op_dict, clamped_bool)."""
    lo, hi = Wmin, Wmax
    op_lo = diode_op(lo, L, Iin, Vdd, case, temp)
    if op_lo["vov"] <= target_vov:
        # even Wmin overdrives too little -> clamp at Wmin (subthreshold regime)
        return lo, op_lo, True
    for _ in range(40):
        mid = (lo*hi)**0.5           # geometric bisection (W spans decades)
        op = diode_op(mid, L, Iin, Vdd, case, temp)
        if abs(op["vov"] - target_vov) < tol:
            return mid, op, False
        if op["vov"] > target_vov:   # too much overdrive -> widen
            lo = mid
        else:
            hi = mid
    return mid, op, False


def calibrate_vbias(geom, Iin, Vdd=5.0, case=0, temp=27, self_biased=False):
    """Search the wide-swing bias drop (vbias, V below Vdd) that MAXIMIZES the
    1%-compliance V_out,max while holding |gain(Vdd/2)-1| < 0.5%.  Returns vbias."""
    import numpy as _np
    best = (None, -1.0)
    for vb in _np.arange(1.5, 2.8+1e-9, 0.05):
        g = dict(geom, vbias=float(vb), Iin=Iin)
        deck, out = deck_dc("cal", "MIR_CW", g, Iin, Vdd, 0, Vdd, 0.05,
                            case=case, temp=temp)
        run(deck, "cal")
        v, i = read_wrdata(out)
        i0 = i[0]
        gmid = i[_np.argmin(abs(v-Vdd/2.0))]/Iin
        below = _np.where(i < 0.99*i0)[0]
        vmax = v[below[0]] if len(below) else v[-1]
        if abs(gmid-1.0) < 0.005 and vmax > best[1]:
            best = (float(vb), float(vmax))
    return best[0] if best[0] is not None else 2.0
