#!/usr/bin/env python3
"""
report_refresh.py -- marker-delimited table injection for the circuits reports
that have no dedicated generator (comparator READMEs / GP-5V deeper docs /
current_mirror_char/MIRROR_CHAR.md).

Ground Rule 2 amendment (v2.1-circuits, orchestrator ruling on the Phase B
escalation): where a report has no generator, every *measured number* must still
trace to a script's output, not a human's typing -- but the hand-authored design
prose (topology diagrams, rationale) is not measurement data and is preserved
verbatim. So each data table lives inside an AUTOGEN fence:

    <!-- AUTOGEN:<type> key=val ... -->
    ...generated table + a provenance line (model_tag / ngspice_version / N)...
    <!-- /AUTOGEN:<type> -->

This module reads the JSON/CSV data of record and rewrites only the fenced blocks.
Prose outside the fences is byte-for-byte untouched.

Usage:
    python report_refresh.py            # rewrite every fence in place
    python report_refresh.py --check    # exit 1 if any fence is stale (CI gate)
    python report_refresh.py --list     # list the fences found and their keys

Fence types (dispatched by the first token after AUTOGEN:):
    cmp_variant   key: subdir=<comparator subdir>   -- the per-variant spec table
    cmp_fin       key: subdir=<gp subdir>           -- the FIN offset/area study table
    sat_margin    key: subdir=<gp subdir>           -- saturation Vds/Vdsat margin table
    sat_icmr      key: subdir=<gp subdir>           -- ICMR band table
    mirror_dc                                       -- MIRROR_CHAR DC metrics table
    mirror_mc                                       -- MIRROR_CHAR MC sigma table
"""
from __future__ import annotations
import argparse
import csv
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent           # circuits/
CMP = HERE / "comparators"
MIR = HERE / "current_mirror_char"

FENCE_RE = re.compile(
    r"(?P<open><!--\s*AUTOGEN:(?P<key>[^\s]+)(?P<args>[^>]*?)-->)"
    r"(?P<body>.*?)"
    r"(?P<close><!--\s*/AUTOGEN:(?P=key)\s*-->)",
    re.DOTALL)


def _args(argstr: str) -> dict:
    return dict(m.split("=", 1) for m in argstr.split() if "=" in m)


def _load(path: Path):
    d = json.load(open(path))
    return d.get("results", d) if isinstance(d, dict) else d


def _prov_from(path: Path) -> str:
    d = json.load(open(path))
    p = d.get("_provenance", {}) if isinstance(d, dict) else {}
    tag = p.get("model_tag", "v2-grounded")
    ng = p.get("ngspice_version", "ngspice-45")
    n = p.get("mc_n") or p.get("nrun") or p.get("n")
    nstr = f" · MC N={n}" if n else ""
    return f"<sub>Generated by `report_refresh.py` from `{path.name}` · models **{tag}** · **{ng}**{nstr}.</sub>"


# --------------------------------------------------------------------- metadata
# Static design labels (role / FIN / input) -- these are NOT measurements; the
# measured numbers all come from the JSON. Kept here so the one shared module owns
# the whole table, per the ruling (one code path).
GP_ROLE = {"gp": "normal", "lo": "lower offset", "lo2": "lowest offset",
           "hyst": "hysteresis", "lp": "low power", "fast": "fast"}
RR_META = {"gp": (1, "normal / low area"), "lo": (2, "lower offset"),
           "lo2": (3, "lowest offset")}


def _num(x, spec="{:.2f}", dash="—"):
    return spec.format(x) if isinstance(x, (int, float)) else dash


def _tpd(r):
    lh, hl = r.get("tpd_lh_ns"), r.get("tpd_hl_ns")
    return f"{_num(lh,'{:.0f}')} / {_num(hl,'{:.0f}')}"


# --------------------------------------------------------------------- generators
def gen_cmp_variant(args: dict) -> str:
    sub = args["subdir"]
    path = CMP / sub / "comparator_results.json"
    rows = _load(path)
    rr = sub.startswith("rail_to_rail")
    out = []
    if rr:
        out.append("| Variant | FIN | role | Iq (µA) | Vos_σ (mV) | Gain (dB) | tpd ↑/↓ (ns) | Area (µm²) |")
        out.append("|---|---|---|---|---|---|---|---|")
        for r in rows:
            v = r["variant"]; fin, role = RR_META.get(v, ("", ""))
            out.append(f"| `{v}` | {fin} | {role} | {_num(r.get('iq_uA'),'{:.1f}')} | "
                       f"{_num(r.get('vos_sigma_mV'))} | {_num(r.get('gain_dB'),'{:.0f}')} | "
                       f"{_tpd(r)} | {_num(r.get('area_um2'),'{:.0f}')} |")
    else:
        out.append("| Variant | In | role | Iq (µA) | Vos_σ (mV) | Gain (dB) | tpd ↑/↓ (ns) | Hyst (mV) | Area (µm²) |")
        out.append("|---|---|---|---|---|---|---|---|---|")
        for r in rows:
            v = r["variant"]; role = GP_ROLE.get(v.split("_", 1)[1], "")
            out.append(f"| `{v}` | {r.get('input','')} | {role} | {_num(r.get('iq_uA'),'{:.1f}')} | "
                       f"{_num(r.get('vos_sigma_mV'))} | {_num(r.get('gain_dB'),'{:.0f}')} | "
                       f"{_tpd(r)} | {_num(r.get('hyst_mV'),'{:.1f}')} | {_num(r.get('area_um2'),'{:.0f}')} |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def gen_cmp_fin(args: dict) -> str:
    sub = args["subdir"]
    path = CMP / sub / "comparator_results.json"
    rows = {r["variant"]: r for r in _load(path)}
    out = ["| `FIN` | role | NIN: Vos_σ / area | PIN: Vos_σ / area | gain |",
           "|---|---|---|---|---|"]
    fin_role = {1: ("gp", "normal"), 2: ("lo", "lower"), 3: ("lo2", "lowest")}
    for fin, (tag, role) in fin_role.items():
        n, p = rows.get(f"nin_{tag}"), rows.get(f"pin_{tag}")
        if not n or not p:
            continue
        g = f"{_num(min(n.get('gain_dB',0), p.get('gain_dB',0)),'{:.0f}')}–{_num(max(n.get('gain_dB',0), p.get('gain_dB',0)),'{:.0f}')} dB"
        out.append(f"| {fin} | `{tag}` ({role}) | {_num(n.get('vos_sigma_mV'))} mV / "
                   f"{_num(n.get('area_um2'),'{:.0f}')} µm² | {_num(p.get('vos_sigma_mV'))} mV / "
                   f"{_num(p.get('area_um2'),'{:.0f}')} µm² | {g} |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def gen_sat_margin(args: dict) -> str:
    sub = args["subdir"]
    path = CMP / sub / "saturation_margin.json"
    d = json.load(open(path))
    out = ["| Variant | min Vds/Vdsat | worst device @ corner | thresh | verdict |",
           "|---|---|---|---|---|"]
    for r in d["results"]:
        out.append(f"| `{r['variant']}` | {_num(r.get('min_ratio'))} | "
                   f"{r.get('worst_dev_label','')} @ {r.get('worst_corner','')} | "
                   f"{_num(r.get('thresh'),'{:.1f}')} | {'PASS' if r.get('pass') else '**FAIL**'} |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def _icmr_cells(r, vdds):
    cells = []
    for v in vdds:
        b = r["icmr_by_vdd"].get(v)
        cells.append(f"{b[0]:.2f}–{b[1]:.2f} V" if b else "none")
    return cells


def gen_sat_icmr(args: dict) -> str:
    """Per-variant ICMR band per VDD (SATURATION_SIGNOFF §ICMR-per-VDD)."""
    sub = args["subdir"]
    path = CMP / sub / "saturation_icmr.json"
    d = json.load(open(path))
    vdds = [str(v) for v in d.get("vdds", [])]
    out = ["| Variant | " + " | ".join(f"{v} V" for v in vdds) + " |",
           "|---|" + "|".join("---" for _ in vdds) + "|"]
    for r in d["results"]:
        out.append(f"| `{r['variant']}` | " + " | ".join(_icmr_cells(r, vdds)) + " |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def gen_sat_joint(args: dict) -> str:
    """Joint NIN+PIN ICMR coverage per VDD (SATURATION_SIGNOFF §joint)."""
    sub = args["subdir"]
    path = CMP / sub / "saturation_icmr.json"
    d = json.load(open(path))
    joint = d.get("joint_gp_icmr_by_vdd", {})
    byv = {str(v): r for r in d["results"] for v in [None]}  # placeholder unused
    nin = next((r for r in d["results"] if r["variant"] == "nin_gp"), None)
    pin = next((r for r in d["results"] if r["variant"] == "pin_gp"), None)
    out = ["| VDD | joint coverage | note |", "|---|---|---|"]
    for v in [str(x) for x in d.get("vdds", [])]:
        j = joint.get(v)
        if not j:
            continue
        lo, hi, gap = j[0], j[1], (len(j) > 2 and j[2])
        if gap and nin and pin:
            pb = pin["icmr_by_vdd"].get(v); nb = nin["icmr_by_vdd"].get(v)
            note = f"**~{nb[0]-pb[1]:.2f} V gap at mid-rail** ({pb[1]:.2f}–{nb[0]:.2f})" if (pb and nb) else "gap at mid-rail"
            cov = f"{pb[0]:.2f}–{pb[1]:.2f} V **and** {nb[0]:.2f}–{nb[1]:.2f} V" if (pb and nb) else f"{lo:.2f}–{hi:.2f} V"
        else:
            note = "continuous"
            cov = f"**{lo:.2f} – {hi:.2f} V**"
        out.append(f"| {v} V | {cov} | {note} |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def gen_char_variant(args: dict) -> str:
    """CHARACTERIZATION §3 full variant table (adds Vos_sys vs the README table)."""
    sub = args["subdir"]
    path = CMP / sub / "comparator_results.json"
    rows = _load(path)
    out = ["| Variant | In | role | Iq (µA) | Vos σ (mV) | Vos_sys (mV) | Gain (dB) | tpd ↑/↓ (ns) | Hyst (mV) | Area (µm²) |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        v = r["variant"]; role = GP_ROLE.get(v.split("_", 1)[1], "")
        out.append(f"| `{v}` | {r.get('input','')} | {role} | {_num(r.get('iq_uA'),'{:.1f}')} | "
                   f"{_num(r.get('vos_sigma_mV'))} | {_num(r.get('vos_sys_mV'),'{:+.2f}')} | "
                   f"{_num(r.get('gain_dB'),'{:.0f}')} | {_tpd(r)} | {_num(r.get('hyst_mV'),'{:.1f}')} | "
                   f"{_num(r.get('area_um2'),'{:.0f}')} |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def gen_char_icmr(args: dict) -> str:
    """CHARACTERIZATION §4 ICMR summary: representative NMOS-in / PMOS-in (gp) per VDD."""
    sub = args["subdir"]
    path = CMP / sub / "saturation_icmr.json"
    d = json.load(open(path))
    vdds = [str(v) for v in d.get("vdds", [])]
    nin = next((r for r in d["results"] if r["variant"] == "nin_gp"), None)
    pin = next((r for r in d["results"] if r["variant"] == "pin_gp"), None)
    out = ["| | " + " | ".join(f"{v} V" for v in vdds) + " |",
           "|---|" + "|".join("---" for _ in vdds) + "|"]
    if nin:
        out.append("| NMOS-in ICMR | " + " | ".join(_icmr_cells(nin, vdds)) + " |")
    if pin:
        out.append("| PMOS-in ICMR | " + " | ".join(_icmr_cells(pin, vdds)) + " |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def gen_mirror_dc(args: dict) -> str:
    path = MIR / "metrics.csv"
    want = {"MIR_S": "simple", "MIR_CS": "std cascode", "MIR_CW": "wide-swing"}
    got = {}
    for r in csv.DictReader(open(path)):
        if r["design"] == "B_10u" and r["corner"] == "TT" and r["temp_C"] in ("27", "27.0"):
            got[r["topo"]] = r
    out = ["| topology (B_10u, TT, 27 °C) | gain @Vdd/2 | λ_eff (/V) | r_out (MΩ) | ramp nonlin | compliance V_out,max (1 %) | area (µm²) |",
           "|---|---|---|---|---|---|---|"]
    for t, lbl in want.items():
        r = got.get(t)
        if not r:
            continue
        out.append(f"| {t} ({lbl}) | {float(r['gain_vddhalf']):.4f} | "
                   f"{float(r['lambda_eff_perV']):.2e} | {float(r['rout_ohm'])/1e6:.1f} | "
                   f"{float(r['ramp_nonlin_pct']):.2f} % | {float(r['vmax_1pct_V']):.2f} V | "
                   f"{float(r['area_um2']):.0f} |")
    out.append("")
    # metrics.csv has no _provenance; stamp from the model tag + mc file's ngspice
    mcp = json.load(open(MIR / "mc_results.json")).get("_provenance", {})
    out.append(f"<sub>Generated by `report_refresh.py` from `metrics.csv` · models "
               f"**{mcp.get('model_tag','v2-grounded')}** · **{mcp.get('ngspice_version','ngspice-45')}**.</sub>")
    return "\n".join(out)


def gen_mirror_mc(args: dict) -> str:
    path = MIR / "mc_results.json"
    d = json.load(open(path))
    res = d["results"]
    out = ["| design | topo | mode | gain | σ/µ (%) | λ σ |",
           "|---|---|---|---|---|---|"]
    for name in d.get("designs", res.keys()):
        for topo in d.get("topos", []):
            for mode in d.get("modes", []):
                r = res.get(name, {}).get(topo, {}).get(mode)
                if not r:
                    continue
                out.append(f"| {name} | {topo} | {mode} | {r['gain_mean']:.4f} | "
                           f"{r['I_mid_sigma_mu']*100:.3f} | {r['lam_std']:.2e} |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


def gen_rr_sat(args: dict) -> str:
    """Rail-to-rail always-on Vds/Vdsat margin per VDD (from run_saturation.py's
    saturation_margin.json). RR is rail-to-rail by construction, so the sign-off is
    the always-on-device margin over the full 0..VDD CM, not an ICMR band."""
    sub = args["subdir"]
    path = CMP / sub / "saturation_margin.json"
    d = json.load(open(path))
    thr = d.get("_provenance", {}).get("thresh")
    out = [f"| VDD | always-on min Vds/Vdsat | binding corner | rule |", "|---|---|---|---|"]
    for r in d["results"]:
        val = f"{r['always_on_min']}" if r["pass"] else f"**{r['always_on_min']} FAIL**"
        out.append(f"| {r['vdd']:g} V | {val} | {r.get('binding_corner','')} | >{thr:g} |")
    out.append("")
    out.append(_prov_from(path))
    return "\n".join(out)


GENERATORS = {
    "cmp_variant": gen_cmp_variant, "cmp_fin": gen_cmp_fin,
    "sat_margin": gen_sat_margin, "sat_icmr": gen_sat_icmr, "sat_joint": gen_sat_joint,
    "rr_sat": gen_rr_sat,
    "char_variant": gen_char_variant, "char_icmr": gen_char_icmr,
    "mirror_dc": gen_mirror_dc, "mirror_mc": gen_mirror_mc,
}

# Reports that carry fences (relative to circuits/).
REPORTS = [
    "comparators/general_purpose/README.md",
    "comparators/general_purpose/CHARACTERIZATION.md",
    "comparators/general_purpose/SATURATION_SIGNOFF.md",
    "comparators/general_purpose_1v8/README.md",
    "comparators/general_purpose_3v3/README.md",
    "comparators/rail_to_rail_5v0/README.md",
    "comparators/rail_to_rail_1v8/README.md",
    "comparators/rail_to_rail_3v3/README.md",
    "current_mirror_char/MIRROR_CHAR.md",
]


def refresh_text(text: str) -> tuple[str, int, int]:
    """Return (new_text, n_fences, n_changed)."""
    n_f = n_c = 0

    def repl(m):
        nonlocal n_f, n_c
        n_f += 1
        key = m.group("key")
        gen = GENERATORS.get(key)
        if gen is None:
            raise SystemExit(f"unknown AUTOGEN fence type: {key}")
        block = gen(_args(m.group("args")))
        new = f"{m.group('open')}\n{block}\n{m.group('close')}"
        old = m.group(0)
        if new != old:
            n_c += 1
        return new

    return FENCE_RE.sub(repl, text), n_f, n_c


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any fence is stale (does not write)")
    ap.add_argument("--list", action="store_true", help="list fences and exit")
    args = ap.parse_args()

    total_f = total_c = stale_files = 0
    for rel in REPORTS:
        path = HERE / rel
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if args.list:
            for m in FENCE_RE.finditer(text):
                print(f"{rel}: {m.group('key')}{m.group('args').rstrip()}")
            continue
        new, n_f, n_c = refresh_text(text)
        total_f += n_f; total_c += n_c
        if n_c:
            stale_files += 1
            if not args.check:
                path.write_text(new, encoding="utf-8", newline="\n")
        status = "stale" if n_c else "ok"
        print(f"  {rel:56s} {n_f:2d} fence(s)  [{status}{'' if not n_c else f': {n_c} changed'}]")

    if args.list:
        return
    if args.check:
        if total_c:
            print(f"\nCHECK FAILED: {total_c} stale fence(s) in {stale_files} file(s). "
                  f"Run `python report_refresh.py` to refresh.")
            sys.exit(1)
        print(f"\nCHECK OK: all {total_f} fences match the current data.")
    else:
        print(f"\nrefreshed {total_c} fence(s) across {total_f} total.")


if __name__ == "__main__":
    main()
