#!/usr/bin/env python3
"""Generate autohv_bicmos180_case_models.inc from models/stat_model.json.

Phase 2, brief S4 as amended by rulings AC1/AC2.

WHAT THIS IS
------------
A LINE TRANSFORM over the authored TEMPLATE (autohv_bicmos180_case_models.inc.in),
emitting autohv_bicmos180_case_models.inc. The generator is a pure function of
(models/stat_model.json, the template): it NEVER reads the file it writes, so a
sigma change propagates and --check can actually fail.

All future non-statistical card edits go into the .in; the .inc is fully generated.

It is a line transform, not a rebuild from scratch. The file carries
918 deterministic card lines, 19 in-card comments, 32 preamble comments, 52 TC_*
tempco params and 4 control params that no statistical model describes; regenerating
those from JSON would mean re-authoring content that is already correct, and would make
`--check` byte-compare meaningless. So this tool rewrites only what the statistical model
owns and passes everything else through unchanged.

WHAT IT REWRITES
----------------
  preamble
    5    one-hot _isXX selector params        -> removed
    186  P_* statistical params               -> removed
    -    (new) Z_* unit-normal draw params    -> one per variable in corners.json
    52   <KIND>_<DEV>_STAT params             -> TT + S*Z or TT*exp(S*Z)
  cards
    124  corner+stat expressions              -> TT + S*Z or TT*exp(S*Z)
    6    corner-only expressions (pclm)       -> collapsed to TT

`pclm` collapsing is authorised, not incidental: dependent_parameters.pclm is
`held_at_TT` -- "no corner or spread data; affects output conductance, not the corner
metric". Its FF/SS spread was +-1.4 % and no variable carries it. This is a real
behaviour change on FF/SS runs and is pre-registered as such.

Z_* RESOLUTION (brief S1.1)
---------------------------
  PROC_ON=0, case>=0    the preset's z from corners.json
  PROC_ON=0, case=-1    per-group c_<GROUP>: 0 -> 0, 1 -> +z_corner, 2 -> -z_corner
                        (z_slow = -z_corner by construction, so only one is stored).
                        z_corner is the per-variable +-3 sigma sign-off vector (ruling
                        Q1), the same convention the presets use -- NOT z_direction,
                        which is the joint-3-sigma point kept for MC work.
  PROC_ON=1             AGAUSS(0,1,1) per draw, ADDED to the corner z so that
                        "process MC centred on a corner" is legal

Corners are NOT generated here (ruling AC2): build_corners.py remains the sole producer
of corners.json and the docs/corners.md table. This tool only reads corners.json.

USAGE
    python tools/gen_models.py            # write the .inc
    python tools/gen_models.py --check    # regenerate to memory, byte-compare, exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from inc_parse import IncParseError, tt_of  # noqa: E402
# One source of truth for kT/q: the harness measured the VBE_*/VF_* directions with this
# value, and the corner z values assume it. A second copy here that drifted would put the
# cards and the measured directions quietly out of step.
from measure_stat_directions import VT_THERMAL  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "models" / "stat_model.json"
CORNERS = ROOT / "models" / "corners.json"
TEMPLATE = ROOT / "autohv_bicmos180_case_models.inc.in"
INC = ROOT / "autohv_bicmos180_case_models.inc"

AUTOGEN = "* AUTOGENERATED by tools/gen_models.py from models/stat_model.json -- do not edit."

# ---------------------------------------------------------------- model reading


def load() -> tuple[dict, dict]:
    return (json.loads(MODEL.read_text(encoding="utf-8")),
            json.loads(CORNERS.read_text(encoding="utf-8")))


def variable_table(model: dict) -> dict[tuple[str, str], tuple[str, str, float]]:
    """(device, card-param) -> (variable, form, sigma), for everything the model owns.

    Only applies_to entries with a `param` are ours; `target` entries (mos_L, mos_W,
    mos_rgate) name physical dimensions the .lib wrappers own and are Phase 3.
    """
    gv = model["global_variables"]
    out: dict[tuple[str, str], tuple[str, str, float]] = {}

    for name, v in gv.items():
        if name.startswith("_") or not isinstance(v, dict):
            continue
        sigma = v.get("sigma")
        for a in v.get("applies_to", []):
            param = a.get("param")
            if not param:
                continue
            for dev in v.get("shared_by", []):
                out[(dev, param)] = (name, a["form"], sigma)

    # templates expand per device, and name the variable <PREFIX>_<DEVICE>
    for tname, prefix in (("_RDSW_template", "RDSW"),
                          ("_CPER_template", "CPER"),
                          ("_VBE_template", "VBE"),
                          ("_BF_template", "BF"),
                          ("_RPAR_template", "RPAR"),
                          ("_VF_template", "VF"),
                          ("_RS_DIO_template", "RS"),
                          ("_CJ_DIO_template", "CJ"),
                          ("_BV_template", "BV")):
        t = gv.get(tname)
        if not isinstance(t, dict):
            continue
        sigma = t.get("sigma")
        members = (t.get("devices") or t.get("layers") or t.get("types") or []) + \
                  t.get("devices_mos", []) + t.get("devices_vdmos", [])
        for a in t.get("applies_to", []) + t.get("applies_to_mos", []) + \
                t.get("applies_to_vdmos", []):
            param = a.get("param")
            if not param:
                continue                      # a wrapper target: the .lib owns it
            # An entry may scope itself to a subset of the template devices.
            scope = a.get("devices") or members
            for dev in scope:
                p = param.replace("*", dev)
                out[(dev, p)] = (f"{prefix}_{dev}", a["form"], sigma)

    # U0 is declared, with sigma forced to 0 on the drift-dominated devices
    u0 = gv.get("_U0_declared", {})
    zero = set(u0.get("sigma_zero_devices", []))
    for a in u0.get("applies_to_mos", []) + u0.get("applies_to_vdmos", []):
        param = a.get("param")
        if not param:
            continue
        for dev in u0.get("devices", []):
            p = param.replace("*", dev)
            out[(dev, p)] = (f"U0_{dev}", a["form"], 0.0 if dev in zero else u0["sigma"])
    return out


def z_variables(corners: dict, table: dict | None = None,
                model: dict | None = None) -> list[str]:
    """Every Z_* the file must declare.

    The union of what corners.json can set AND what the model owns. Variables pruned
    from the directions for having no lever at the bench (BV_*, CJ_*, JS_MOS) still
    need a declaration: their card expression references them, they resolve to 0 at
    every preset (correct -- no corner moves them), and they remain settable under
    PROC_ON=1. Declaring only the corner keys left 20 dangling references.
    """
    names: set[str] = set()
    for p in corners["presets"].values():
        names |= set(p["z"])
    for r in corners["per_group"].values():
        names |= set(r["z_corner"])
    if table:
        names |= {var for (_dev, _param), (var, _form, sig) in table.items() if sig}
    if model is not None:
        # Wrapper targets (applies_to entries with `target` rather than `param`) get
        # no variable_table entry, because the .inc emits no card line for them. The
        # authored .lib still references their Z_, so declare it here.
        for tname, tpl in model["global_variables"].items():
            if not isinstance(tpl, dict) or not tname.endswith("_template"):
                continue
            prefix = tname[1:].replace("_template", "")
            if not tpl.get("sigma"):
                continue
            for a in tpl.get("applies_to", []):
                if a.get("param") or not a.get("target"):
                    continue
                for dev in a.get("devices", []):
                    names.add(f"{prefix}_{dev}")
    return sorted(names)


# ---------------------------------------------------------------- emission


def emission_table(src: list[str]) -> dict[str, float]:
    """{card: emission coefficient} -- diode `n`, BJT `nf`, read from the template.

    A pre-scan is necessary rather than a lookup while transforming: `n` sits BELOW `is`
    in every card, so a single forward pass does not yet know it when it rewrites `is`.

    Read, never typed (ruling Finding A). The six diodes run n = 1.03 to 1.22 and two of
    the four BJTs carry nf = 1.02 / 1.03, so a single constant is wrong by up to 22 %.
    """
    out: dict[str, float] = {}
    card = None
    for line in src:
        m = re.match(r"\.model\s+(\S+)\s", line, re.I)
        if m:
            card = m.group(1)
            continue
        if card is None:
            continue
        p = re.match(r"\+\s*(n|nf)\s*=\s*(.+?)\s*$", line, re.I)
        if p and card not in out:
            try:
                out[card] = tt_of(p.group(2))
            except IncParseError as exc:
                raise SystemExit("gen_models: cannot read %s.%s: %s"
                                 % (card, p.group(1), exc))
    return out


def expression(tt: float, form: str, sigma: float, var: str, n: float = 1.0) -> str:
    """One statistical parameter as a single expression in its unit-normal draw."""
    if not sigma:
        return "%.6g" % tt
    if form == "additive":
        return "{%.6g + %.6g*Z_%s}" % (tt, sigma, var)
    if form == "exp_v":
        # The declared variable is a VOLTAGE spread (sigma_VBE = 2 mV, sigma_VF = 2.67 mV)
        # but the card parameter it drives is a current. IS = IS_TT*exp(dV/V_T), so the
        # ln-current sigma is sigma_V/V_T. Fold it here, at generation, so V_T never
        # appears in the model file and the card is a plain multiplicative draw (ruling
        # Q2). V_T is frozen at 27 C deliberately: the physical variable is the saturation
        # current, and a fixed IS multiplier is that physics at every temperature -- the
        # 2 mV is merely the 27 C quote of it, the way datasheets quote it. The equivalent
        # Vbe spread then shrinks with V_T at high temperature, which is correct.
        # Sign is positive to match measure_stat_directions.perturbed(), which measured
        # the direction as tt*exp(+sigma*scale*z); the corner z values assume that sign.
        # `n` is the card's own emission coefficient, per the template's derivation
        # IS = IS_TT*exp(dV/(n*V_T)) -- it must match the harness's scale exactly or the
        # cards and the measured directions describe different distributions.
        return "{%.6g*exp(%.6g*Z_%s)}" % (tt, sigma / (n * VT_THERMAL), var)
    return "{%.6g*exp(%.6g*Z_%s)}" % (tt, sigma, var)


def z_block(corners: dict, table: dict, model: dict) -> list[str]:
    """The Z_* preamble: corner resolution, per-group override, native MC."""
    out = [
        "* --- corner / MC interface (ruling AC2: corners.json is built by build_corners.py) ---",
        "* Every statistical parameter is one expression in a unit-normal Z_*.",
        "*   PROC_ON=0, case>=0 : Z from the preset",
        "*   PROC_ON=0, case=-1 : Z from c_<GROUP>  (0 typ, 1 fast/hi, 2 slow/lo)",
        "*   PROC_ON=1          : AGAUSS(0,1,1) added to the corner z, so process MC",
        "*                        centred on a corner is legal",
        "",
    ]
    groups = sorted(corners["per_group"])
    for g in groups:
        out.append(".param c_%s=0" % g)
    out.append("")

    presets = corners["presets"]
    for var in z_variables(corners, table, model):
        # preset contribution
        terms = []
        for case in sorted(presets, key=int):
            v = presets[case]["z"].get(var)
            if v:
                terms.append("(case==%s)*%.6g" % (case, v))
        preset_expr = " + ".join(terms) if terms else "0"
        # per-group contribution, active only at case=-1
        per = []
        for g in groups:
            v = corners["per_group"][g]["z_corner"].get(var)
            if v:
                per.append("(c_%s==1)*%.6g + (c_%s==2)*%.6g" % (g, v, g, -v))
        per_expr = " + ".join(per) if per else "0"
        # The MC draw must bind to the WHOLE conditional, not to its false branch:
        # at case = -1 the per-group mode would otherwise get no process draw.
        out.append(".param Z_%s={((case==-1) ? (%s) : (%s)) + PROC_ON*AGAUSS(0,1,1)}"
                   % (var, per_expr, preset_expr))
    out.append("")
    return out


def generate() -> str:
    model, corners = load()
    table = variable_table(model)
    if TEMPLATE.resolve() == INC.resolve():
        raise SystemExit("gen_models: template and output are the same file; "
                         "a generator must never read the file it writes")
    src = TEMPLATE.read_text(encoding="utf-8").splitlines()
    emission = emission_table(src)

    out: list[str] = []
    card: str | None = None
    i = 0
    n = len(src)
    while i < n:
        line = src[i]

        # header: stamp the autogen marker after the first rule line.
        # Only if it is not already there -- this tool is a line transform over the
        # .inc, so regenerating an already-generated file must be idempotent or
        # --check can never go green after a write.
        if i == 0:
            out.append(line)
            out.append(AUTOGEN)
            i += 1
            continue

        # preamble: drop the selector block and the P_* block, insert Z_* once
        if re.match(r"\.param\s+_is", line):
            if not any(l.startswith(".param Z_") for l in out):
                out.extend(z_block(corners, table, model))
            i += 1
            continue
        if re.match(r"\.param\s+P_", line):
            i += 1
            continue
        if line.startswith("* --- one-hot corner selectors") or \
                line.startswith("* --- statistical parameters"):
            i += 1
            continue

        # _STAT params: TT + S*Z
        m = re.match(r"(\.param\s+)(\w+)_(\w+)_STAT(\s*=\s*)(.+)", line)
        if m:
            kind, dev, expr = m.group(2), m.group(3), m.group(5)
            try:
                tt = tt_of(expr)
            except IncParseError:
                tt = None
            key = (dev, "%s_%s_STAT" % (kind, dev))
            ent = table.get(key)
            if tt is not None and ent:
                var, form, sigma = ent
                out.append("%s%s_%s_STAT%s%s"
                           % (m.group(1), kind, dev, m.group(4),
                              expression(tt, form, sigma, var)))
            else:
                out.append(line)
            i += 1
            continue

        mm = re.match(r"\.model\s+(\S+)\s", line, re.I)
        if mm:
            card = mm.group(1)
            out.append(line)
            i += 1
            continue
        if card and re.match(r"\+\s*\)", line):
            card = None
            out.append(line)
            i += 1
            continue

        # card parameter lines
        p = re.match(r"(\+\s*)(\w+)(\s*=\s*)\{(.+)\}(.*)$", line)
        if card and p:
            param, expr, tail = p.group(2), p.group(4), p.group(5)
            # Only a corner selector or a P_ draw marks a line this tool owns.
            # A line whose sole statistical content is a *_STAT reference is a
            # tempco wrapper (vto/kp/rd/rs on the VDMOS cards): its statistics
            # live in the _STAT declaration, which is rewritten in the preamble,
            # so the card line passes through untouched.
            # NB: a bare `"P_" in expr` substring test is WRONG -- it matches inside
            # KP_<DEV>_STAT and TC_KP_<DEV>, so the 13 kp tempco wrappers were
            # misrouted into the rewrite branch and raised. Match the parameter
            # name at a word boundary instead.
            if "_isTT" in expr or re.search(r"\bP_[A-Z]", expr):
                try:
                    tt = tt_of(expr)
                except IncParseError as exc:
                    raise SystemExit("gen_models: %s.%s: %s" % (card, param, exc))
                dev = card[:-4] if card.endswith("_INT") else card
                ent = table.get((dev, param))
                if ent:
                    var, form, sigma = ent
                    out.append("%s%s%s%s%s" % (p.group(1), param, p.group(3),
                                               expression(tt, form, sigma, var,
                                                          emission.get(card, 1.0)),
                                               tail))
                else:
                    # corner-only (pclm): held_at_TT per dependent_parameters
                    out.append("%s%s%s%.6g%s" % (p.group(1), param, p.group(3), tt, tail))
                i += 1
                continue

        out.append(line)
        i += 1

    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="regenerate and byte-compare; exit 1 on drift")
    args = ap.parse_args(argv)

    text = generate()
    if args.check:
        current = INC.read_text(encoding="utf-8")
        if current != text:
            print("stale: %s differs from the generator output" % INC.name)
            return 1
        print("ok: %s is current" % INC.name)
        return 0

    INC.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %s" % INC.name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
